name: terraform apply on master push

on:
  push:
    branches: [ master ]

env:
  TF_VERSION: 0.12.24
  TF_WORKING_DIR: .
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BACKEND_ROLE_ARN: ${{ secrets.AWS_BACKEND_ROLE_ARN }}
  BUCKEND_BUCKET: ${{ secrets.AWS_BACKEND_BUCKET }}
  BACKEND_REGION: ap-northeast-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ env.TF_WORKING_DIR }}
          tf_actions_comment: false

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.TF_WORKING_DIR }}
          tf_actions_comment: false
          args: '-backend=true -backend-config="role_arn=${{ env.AWS_BACKEND_ROLE_ARN }}" -backend-config="bucket=${{ env.BUCKEND_BUCKET }}" -backend-config="key=${{ github.repository }}/terraform.tfstate" -backend-config="region=${{ env.BACKEND_REGION }}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ${{ env.TF_WORKING_DIR }}
          tf_actions_comment: false
          args: '-var-file=variables.tfvars'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
